# TODO: `clippy::needless_range_loop` is currently buggy (https://github.com/rust-lang/rust-clippy/issues/3032)
# Remove it from this file when that bug is resolved.

language: rust
jobs:
  include:
    - stage: test
      os: linux
      before_script:
        - rustup toolchain install stable
        - rustup component add --toolchain stable clippy-preview || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
        - rustup component add rustfmt
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt --all -- --check
        - cargo +stable clippy --all-targets --all-features -- -D warnings -A clippy::unreadable_literal -A clippy::needless_range_loop -A clippy::float_cmp -A clippy::comparison-chain -A clippy::needless-doctest-main -A clippy::missing-safety-doc
    - stage: test
      os: osx
      before_script:
        - rustup toolchain install stable
        - rustup component add --toolchain stable clippy-preview || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
        - rustup component add rustfmt
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt --all -- --check
        - cargo +stable clippy --all-targets --all-features -- -D warnings -A clippy::unreadable_literal -A clippy::needless_range_loop -A clippy::float_cmp -A clippy::comparison-chain -A clippy::needless-doctest-main -A clippy::missing-safety-doc
        
    # deploy crates and documentation conditionally
    # deploy on cargo if tagged master release
    - stage: deploy
      os:
        - linux
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+ AND type != pull_request
      # our encrypted cratesio token
      env:
        - secure: "JXnAcT0TcXb0lAs4A53wsnUTaJFZu2uRECYGz3fYKcFlI+47Htl6j7BVI25PRouREObWCAf30VGXWYCzp1Jn/KftXNjEfzduw794Dl1g22HiazGm0k7D3ONTDinsgbadJ0QoCRYthjwFvVXuLNKfI1H+/6JddX5RDhIhvE82O1yL3T3oh4keGwIrDh0snwoFXRxFJGyfREHkF7dztZgwxSXctTPcBlfrbSjWIea84eonXr9SU229gKeXS3sKd/mjwzubJ4bzWvM9nhpu4dZtxvAm95Af1akAvxPnXM5vjbXkrJZflAIxs6Qu6sc4bqYvTQiDW5rJUNz8Sa0z2ESOiu0wQVC7Tj7WtUlZ1EEwemb7QUOw05Ocv+LPqZrEXRPtJLa952OUhIOyWRHnEehKmE34gILW1HbgOTO5jqdTQbRpPlXrXL6QdCqqBvYkgMkuiFSgXdZiuerYY6yGHhjuS3kd77XPBnWl4cU/S3pESkH7DNvjraI6DoyBIh62Ua3oYeAwFSmyvB0bB0BUaw2R+sE6ljxL45HOT3NeB/Pxwga9b2oxzlpxAv3kRyWLL155eJt7pNYAM+12wFjvnSDR8lPKsY5c+fow527ZW+4++/N1Qc85+mRFiwfIEYmkGmjqm50TUB0TxdQyyWAe5Yq+YnKYsbdjMNiqgTaomONW6sw=" 
      script:
        - |
          cargo publish --token ${CRATESIO_TOKEN} --manifest-path Cargo.toml
    # deploy docs if master and not PR
    - stage: docs
      os:
        - linux
      if: (branch = master OR tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+) AND type != pull_request
      env:
        - secure: "ebnD6yB0MGag1xkNgaOfJx3NXJVuybTlctEJ0tiTkWntEY3kWrc+I3MNOtG40cKC/B/Z9oqYyY6rD0rbfa8NWBFAJ5i8BMJ0IwSRKx/1f7rQgavn7YOXzPGY+CT3qM6KEPwILtIp53KfdIqGl+iPOPZT5W7PZRxg4+QtlfSIrtz/pPjjR8s1LTiD3/KAKEiFLiHP4+w9tKrVpsgxyTsDSx5f21zNOM4Nzg7waz7IoWHIEDsj0ILR7j/nMdyrGMjW14ENyrXVLEnS8p68BREkuV4L2aB2b8EtjtBRNZNWRQXhGy5/SVao+LWIoRJ7h+jJyGqxlP5z1j0QjAUBazi3uWaljL8REpErbssxxuX+KTa4nIvmr2H1E+eYQV7ndMQ2js6bbCXlZQwM9jezQfQkaxYbYJf4Fh9G5c6kUlrjfGYdKIEzxd1P4y+yP88zcgJutXs4Tl/BmvJUIfep1COwf4mwRuvgx0SNRIzZCAtBOSHtcOxqzUaVbd8N2JBKyBjUwXPK0hVXkMXxQfURmnAOceIPQIiHBFtylKOiS1Cn75q6M+7DYhh44uFpLAVrzV5x+3aKls8eW+FXLJYIUBgFfFtkCEDSr+7YNJXzwvYAQYJPuxH0itNsN0P3F03hNZSq0tyjLTc3peqA92w3Id8xp0J/Ub0aps2oRH4IYZE/+o8="
      script: 
        - |
          cargo doc --all --no-deps &&
          echo '<meta http-equiv=refresh content=0;url=vst/index.html>' > target/doc/index.html &&
          sudo pip install ghp-import &&
          ghp-import -n target/doc &&
          git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
